#' Read a Lotek Acoustic Receiver File Version 2
#'
#' This function takes a V2 raw acoustic detection file generated by a Lotek
#' JSATS receiver and processes it into a dataframe which can be used by
#' the filtering functions in this package.This is called within read_jsats().
#'
#' @param path the path to the folder containing the desired file
#' @param file the path of the desired file
#' @param timezone the Olsen Named time zone, default is "America/Los_Angeles"
#' @param sensor Logical, does the tag have an environmental sensor? default is FALSE
#' @returns A dataframe converting the raw detection data into rows of detections
#' @export
#' @examples
#' # see read_ats or read_tekno for example usage
#'
read_lotek_v2 <- function(path, file, sensor = FALSE,
                          timezone="America/Los_Angeles"){
  #Serial number now has to be retrieved from inside file
  ReceiverSN <- read.delim(file.path(path,file),
                         skip = 18,
                         nrows = 1,
                         sep = ":",
                         header = FALSE)
  ReceiverSN <- ReceiverSN[1,2]
  ReceiverSN <- trimws(ReceiverSN)

  #Format changed from V1
  if(sensor == TRUE){
  LOT = read.delim(file.path(path,file),
                   sep = "",
                   colClasses = c(character(),
                                  character(),
                                  numeric(),
                                  character(),
                                  character(),
                                  numeric(),
                                  numeric()),
                   col.names = c("Date","Time_Local","FS","Tag_Decimal",
                                 "Tag Type","Sensor","P"),
                   skip = 45)
  } else {
    LOT = read.delim(file.path(path,file),
                     sep = "",
                     colClasses = c(character(),
                                    character(),
                                    numeric(),
                                    character(),
                                    character(),
                                    numeric()),
                     col.names = c("Date","Time_Local","FS","Tag_Decimal",
                                   "Tag Type","P"),
                     skip = 45)
                   }

  LOT$ReceiverSN <- as.numeric(gsub("WHS4K-","",ReceiverSN)) #Turn the file name into serial
  LOT$DateTime_Local =  as.POSIXct(paste(LOT$Date,LOT$Time_Local, sep = " "), #Convert character DateTime to real DT
                                   format = ("%m/%d/%y %H:%M%OS"),
                                   tz = timezone)
  LOT$Tag_Hex = broman::convert2hex(LOT$Tag_Decimal)
  LOT$FS = lubridate::seconds(LOT$FS) #Convert fractional seconds from number to seconds
  LOT$DateTime_Local = LOT$DateTime_Local+LOT$FS #Add them together
  LOT$Filename = stringr::str_split(file, pattern = '\\.')[[1]][1]
  LOT$Make = "Lotek"
  LOT <- dplyr::select(.data =  LOT, ReceiverSN, Make, DateTime_Local,
                       Tag_Decimal, Tag_Hex)
  LOT
}
